// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4I15Wv8vY0XzELYTSfn1YilbNRSr9iQ',
    appId: '1:832884463464:web:1e42c91a14e3ff80a968dd',
    messagingSenderId: '832884463464',
    projectId: 'test-project-52b47',
    authDomain: 'test-project-52b47.firebaseapp.com',
    storageBucket: 'test-project-52b47.appspot.com',
    measurementId: 'G-ZBWXK6TE0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Yo3ijcpdsywnSnzFTdT0WUZe1Scd-v0',
    appId: '1:832884463464:android:f108feb0e3240e7ba968dd',
    messagingSenderId: '832884463464',
    projectId: 'test-project-52b47',
    storageBucket: 'test-project-52b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPH-VuqJxmw0VFc0Y8mjAEjIv_mLHgT8',
    appId: '1:832884463464:ios:c770d66f86f8cf21a968dd',
    messagingSenderId: '832884463464',
    projectId: 'test-project-52b47',
    storageBucket: 'test-project-52b47.appspot.com',
    iosClientId: '832884463464-era7jnm8u08jvbpbvq4t27hkcagmu40t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPH-VuqJxmw0VFc0Y8mjAEjIv_mLHgT8',
    appId: '1:832884463464:ios:c770d66f86f8cf21a968dd',
    messagingSenderId: '832884463464',
    projectId: 'test-project-52b47',
    storageBucket: 'test-project-52b47.appspot.com',
    iosClientId: '832884463464-era7jnm8u08jvbpbvq4t27hkcagmu40t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
